<a href="https://colab.research.google.com/github/FaizaAli-Dev/AI-DS-Projects/blob/projects/SVM_on_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/titanic_clean.csv')
df

NameError: ignored

In [ ]:
df.dtypes

PassengerId     int64
Survived        int64
Pclass          int64
Sex            object
SibSp           int64
Parch           int64
Embarked       object
Title          object
GrpSize        object
FareCat        object
AgeCat         object
dtype: object

In [ ]:
df=pd.get_dummies(df,columns=['Pclass', 'Sex', 'Embarked', 'Title',
'GrpSize', 'FareCat', 'AgeCat'])

In [ ]:
X = df.drop(['Survived','PassengerId'],axis=1)
Y = df['Survived']
x_train,X_test,y_train,Y_test=train_test_split(X,Y,test_size=0.3,
random_state=100,shuffle=True)
X

,SibSp,Parch,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,...,FareCat_100+,FareCat_25-40,FareCat_40-70,FareCat_70-100,FareCat_Oct-25,AgeCat_0-16,AgeCat_16-32,AgeCat_32-48,AgeCat_48-64,AgeCat_64+
0,1,0,0,0,1,0,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,1,0,1,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,0,0,0,1,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,1,0,1,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,1,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,0,0,1,0,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
887,0,0,0,1,0,0,1,0,0,1,...,0,0,0,0,1,0,1,0,0,0
888,0,0,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
889,0,0,1,0,0,0,1,1,0,0,...,0,1,0,0,0,0,1,0,0,0
890,0,0,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
svm_model = SVC(kernel='linear')

In [ ]:
svm_model.fit(x_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred = svm_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8432835820895522